# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleardata',
            name='id',
        ),
        migrations.AlterField(
            model_name='cleardata',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
